---
- name: Official K8s Stack Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy the Web-DB Stack
      kubernetes.core.k8s:
        state: present
        # Point to your blueprint
        src: "{{ playbook_dir }}/web-db-stack.yml"
