---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clean Manifest Content
      set_fact:
        clean_manifest: "{{ manifest_content | regex_replace('^```yaml\\n|```$', '') | trim }}"

    - name: Apply Manifest via Kubectl
      shell: |
        echo '{{ clean_manifest }}' | kubectl apply -f -
      register: kubectl_out

    - name: Show Result
      debug:
        var: kubectl_out.stdout_lines
