---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clean Manifest Content
      set_fact:
        clean_manifest: "{{ manifest_content | regex_replace('^```yaml\\n|```$', '') | trim }}"

    - name: Deploy to Kubernetes
      kubernetes.core.k8s:
        definition: "{{ clean_manifest }}"
        namespace: demo-webdb
        state: present
        # These look up the internal AWX connection automatically
        host: https://kubernetes.default.svc
        ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        token: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
        validate_certs: false
