---
- name: Deploy Full Vint Cerf Stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Download Tooling
      shell: |
        curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
      args:
        chdir: /tmp

    - name: Generate Secret Manifest
      shell: |
        /tmp/kubectl create secret generic gpt-secret \
        --namespace=demo-webdb \
        --from-literal=api-key="{{ lookup('ansible.builtin.env', 'OPENAI_API_KEY') }}" \
        --dry-run=client -o yaml > /tmp/gpt-secret.yml
      # We don't need cluster auth for a 'dry-run'

    - name: Apply OpenAI Secret to Cluster
      shell: "/tmp/kubectl apply -f /tmp/gpt-secret.yml"
      environment:
        K8S_AUTH_API_KEY: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
        K8S_AUTH_HOST: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"

    - name: Deploy Postgres and Adminer
      shell: "/tmp/kubectl apply -f {{ playbook_dir }}/web-db-stack.yml"
      environment:
        K8S_AUTH_API_KEY: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
        K8S_AUTH_HOST: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"

    - name: Deploy GPT Client
      shell: "/tmp/kubectl apply -f {{ playbook_dir }}/gpt-client.yml"
      environment:
        K8S_AUTH_API_KEY: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
        K8S_AUTH_HOST: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"
