---
- name: Build the Web and Database Stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy the stack using kubectl
      command: "kubectl apply -f {{ playbook_dir }}/web-db-stack.yml"
      register: k8s_output

    - name: Show Kubernetes Output
      debug:
        var: k8s_output.stdout_lines
