---
- name: Deploy Database and Adminer Stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Apply Kubernetes Manifest
      kubernetes.core.k8s:
        state: present
        # Point to the file directly - the module handles the '---' separators!
        src: "{{ playbook_dir }}/web-db-stack.yml"
        wait: yes
