---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  vars:
    # This reads the internal K8s token automatically provided to the AWX pod
    k8s_token: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    k8s_api: "https://kubernetes.default.svc"

    # We'll default to 'demo-webdb', but GPT can override this
    target_ns: "demo-webdb"

  tasks:
    - name: Deploy ConfigMap via API (Test Case)
      ansible.builtin.uri:
        url: "{{ k8s_api }}/api/v1/namespaces/{{ target_ns }}/configmaps"
        method: POST
        body_format: json
        body: "{{ manifest_content | from_yaml }}"
        status_code: [201, 409] # 201 is Created, 409 means it already exists
        headers:
          Authorization: "Bearer {{ k8s_token }}"
          Content-Type: "application/json"
        validate_certs: false
