---
- name: Managed Kubernetes Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run kubectl apply inside a temporary container
      shell: |
        kubectl run ansible-deploy-runner \
        --image=bitnami/kubectl:latest \
        --restart=Never \
        --overrides='{ "spec": { "serviceAccountName": "awx" } }' \
        --rm -i -- apply -f - <<EOF
        {{ lookup('file', playbook_dir + '/web-db-stack.yml') }}
        EOF
