---
- name: Deploy Full Vint Cerf Stack
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # We define these once to keep the commands clean
    k8s_server: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"
    k8s_token: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
    k8s_opts: "--server={{ k8s_server }} --token={{ k8s_token }} --insecure-skip-tls-verify=true"

  tasks:
    - name: Download Tooling
      shell: |
        curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
      args:
        chdir: /tmp

    - name: Create Kubernetes Secret for OpenAI
      shell: |
        /tmp/kubectl {{ k8s_opts }} create secret generic gpt-secret \
        --namespace=demo-webdb \
        --from-literal=api-key="{{ lookup('ansible.builtin.env', 'OPENAI_API_KEY') }}" \
        --dry-run=client -o yaml | /tmp/kubectl {{ k8s_opts }} apply -f -

    - name: Deploy Postgres and Adminer
      shell: "/tmp/kubectl {{ k8s_opts }} apply -f {{ playbook_dir }}/web-db-stack.yml"

    - name: Deploy GPT Client
      shell: "/tmp/kubectl {{ k8s_opts }} apply -f {{ playbook_dir }}/gpt-client.yml"
