---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  vars:
    # Use the environment variables AWX injects from your K8s Credential
    k8s_api_host: "{{ lookup('env', 'K8S_AUTH_HOST') | default('https://kubernetes.default.svc', true) }}"
    k8s_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') | default(lookup('env', 'K8S_AUTH_TOKEN'), true) }}"

  tasks:
    - name: Clean Manifest Content
      set_fact:
        clean_manifest: "{{ manifest_content | regex_replace('^```yaml\\n|```$', '') | trim }}"

    - name: Deploy to Kubernetes
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        api_key: "{{ k8s_api_key }}"
        definition: "{{ clean_manifest }}"
        namespace: demo-webdb
        state: present
        validate_certs: false
