---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy to Kubernetes API
      ansible.builtin.uri:
        # These variables come automatically from the AWX Kubernetes Credential
        url: "{{ lookup('env', 'K8S_AUTH_HOST') }}/api/v1/namespaces/demo-webdb/configmaps"
        method: POST
        body_format: json
        body: "{{ manifest_content | from_yaml }}"
        status_code: [201, 409]
        headers:
          Authorization: "Bearer {{ lookup('env', 'K8S_AUTH_API_KEY') }}"
          Content-Type: "application/json"
        validate_certs: false
