---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  vars:
    k8s_api: "{{ lookup('env', 'K8S_AUTH_HOST') | default('https://kubernetes.default.svc', true) }}"
    k8s_token: "{{ lookup('env', 'K8S_AUTH_API_KEY') | default(lookup('env', 'K8S_AUTH_TOKEN'), true) }}"

  tasks:
    - name: Parse Manifests
      set_fact:
        manifest_list: "{{ manifest_content | regex_replace('^```yaml\\n|```$', '') | from_yaml_all | select('ne', None) | list }}"

    - name: Deploy Resources via REST API
      ansible.builtin.uri:
        # Fixed URL: Namespaces use a different path than namespaced resources
        url: >-
          {{ k8s_api }}{{ (item.apiVersion == 'v1') | ternary('/api/v1', '/apis/' + item.apiVersion) }}{{ (item.kind == 'Namespace') | ternary('', '/namespaces/demo-webdb') }}/{{ (item.kind | lower) }}s/{{ item.metadata.name }}?fieldManager=ansible-ztp
        method: PATCH
        body_format: json
        body: "{{ item }}"
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ k8s_token }}"
          Content-Type: "application/apply-patch+yaml"
        validate_certs: false
      loop: "{{ manifest_list }}"
      loop_control:
        label: "Deploying {{ item.kind }}: {{ item.metadata.name }}"
