---
- name: Zero Touch Deployer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply Manifest from GPT
      kubernetes.core.k8s:
        state: present
        definition: "{{ manifest_content }}"
