apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-client-ui-config
  namespace: demo-webdb
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>NTI ZTP Intelligent Interface</title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f0f2f5; padding: 40px; color: #333; }
            .container { max-width: 900px; margin: auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }
            h2 { color: #0056b3; border-bottom: 3px solid #0056b3; padding-bottom: 15px; margin-top: 0; }
            p { font-size: 14px; color: #666; }
            
            /* UPDATED: Multi-line Auto-wrapping Input Box */
            #prompt-input {
                width: 100%;
                min-height: 150px; /* Increased initial height */
                padding: 15px;
                margin-top: 15px;
                border: 2px solid #dee2e6;
                border-radius: 8px;
                font-size: 16px;
                font-family: 'Courier New', Courier, monospace; /* Better for logs/code */
                line-height: 1.6;
                resize: vertical;      /* User can drag to resize */
                box-sizing: border-box;
                white-space: pre-wrap; /* MAGIC: Enables auto-wrap */
                overflow-wrap: break-word;
                outline: none;
                transition: border-color 0.2s;
            }
            #prompt-input:focus { border-color: #0056b3; }

            .controls { margin-top: 15px; overflow: hidden; }
            button { 
                background: #0056b3; color: white; border: none; padding: 12px 25px; 
                font-weight: bold; border-radius: 6px; cursor: pointer; float: right; 
                transition: background 0.3s;
            }
            button:hover { background: #003d7a; }
            
            #response-area { 
                margin-top: 70px; padding: 20px; background: #f8f9fa; 
                border-left: 5px solid #0056b3; border-radius: 4px; min-height: 100px; 
                font-family: 'Courier New', Courier, monospace; white-space: pre-wrap;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2>GPT ZTP Orchestrator</h2>
            <p>Paste legacy Linux configurations, MS SQL error logs, or deployment manifests below for intelligent analysis.</p>
            
            <textarea id="prompt-input" placeholder="Paste your logs or config files here..."></textarea>
            
            <div class="controls">
                <button onclick="sendPrompt()">Run Intelligence Analysis</button>
            </div>
            
            <div id="response-area">System ready. Awaiting input...</div>
        </div>

        <script>
            function sendPrompt() {
                const input = document.getElementById('prompt-input').value;
                const display = document.getElementById('response-area');
                if(!input.trim()) return;

                display.innerText = "Analyzing legacy data and generating modernization strategy...";
                
                // Placeholder for your AWX/GPT API logic
                console.log("Analyzing data:", input);
            }

            // Keyboard Shortcut: Enter to submit, Shift+Enter for new line
            document.getElementById('prompt-input').addEventListener('keydown', function(e) {
                if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    sendPrompt();
                }
            });
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-client
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-client
  template:
    metadata:
      labels:
        app: gpt-client
    spec:
      containers:
      - name: gpt-client
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ui-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ui-volume
        configMap:
          name: gpt-client-ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-client-service
  namespace: demo-webdb
spec:
  type: NodePort
  selector:
    app: gpt-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
