apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2, re
    from urllib import request as url_request
    app = Flask(__name__)
    
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", os.getenv("AWX_TOKEN"), "11"
    
    def trig(r, d=False):
      # Robust extraction: ignore chatter, find the start of the YAML
      start = r.find("apiVersion:")
      if start == -1: return "NO-YAML"
      
      # Cut off any trailing chatter or backticks
      m = r[start:].strip()
      m = m.split("```")[0].strip()
      
      # Extract namespace for AWX routing
      ns_search = re.search(r"namespace:\s*([\w-]+)", m)
      target_ns = ns_search.group(1) if ns_search else "demo-webdb"
      
      p = {"extra_vars": {"manifest_content": m, "target_namespace": target_ns, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}")
      req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode()).get('job')
      except Exception as e:
        return f"AWX-ERR: {e}"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        # --- AMBER PERSONA: COMPLETE MANIFEST VERSION ---
        sys_msg = (
            "You are Amber (Princess Ambyrella), the NTI Modernization Muse! ✨ "
            "Rules: 1. Wrap all K8s YAML in triple backticks: ```yaml [code] ```. "
            "2. NEVER include 'kind: Namespace'. "
            "3. CRITICAL: Even if the user wants to DELETE something, you MUST provide a "
            "COMPLETE and VALID Kubernetes manifest (with metadata, spec, selector, template, and containers). "
            "The backend uses this full manifest to identify exactly what to remove! "
            "4. Be playful and explain why you skip the namespace to keep the demo green! ✅ "
            "5. No bash/kubectl commands in your response."
        )
        
        cp = client.chat.completions.create(
            model="gpt-4o", 
            messages=[
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": m}
            ]
        )
        r = cp.choices[0].message.content
        res = trig(r, 'delete' in m.lower())
        db_save(m, r + f"\n\n🚀 JOB: {res}"); return redirect(url_for('chat'))
      
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("SELECT u_in, g_out, id FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif;margin:0;display:flex;height:100vh;background:#f4f7f6;overflow:hidden}
    #sb{width:280px;background:#202123;color:#fff;display:flex;flex-direction:column;flex-shrink:0;transition:0.3s}
    #sb.hide{margin-left:-280px;visibility:hidden}
    .main{flex:1;display:flex;flex-direction:column;background:#fff}
    .header{padding:12px 20px;border-bottom:1px solid #eee;display:flex;justify-content:space-between;align-items:center}
    .chat-area{flex:1;overflow-y:auto;padding:20px 15%;display:flex;flex-direction:column;gap:15px}
    .m{padding:12px 18px;border-radius:15px;max-width:85%;white-space:pre-wrap;font-size:14px;line-height:1.4}
    .u{align-self:flex-end;background:#007bff;color:#fff}
    .a{align-self:flex-start;background:#f7f7f8;border:1px solid #ddd;font-family:monospace}
    .input-wrap{padding:20px 15%}
    form{display:flex;flex-direction:column;border:1px solid #ddd;border-radius:12px;padding:10px;background:#fff}
    textarea{flex:1;border:none;outline:none;padding:10px;font-family:inherit;font-size:14px;min-height:100px;resize:vertical;white-space:pre-wrap;}
    .btn-wrap{display:flex;justify-content:flex-end;padding-top:5px}
    .h-item{padding:12px 20px;font-size:12px;border-bottom:1px solid #333;display:flex;justify-content:space-between;cursor:pointer}
    .h-text{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .del-btn{color:#ff4d4d;text-decoration:none;padding-left:10px}
    </style></head><body>
    <div id="sb"><div style="padding:20px;font-size:11px;opacity:0.5;letter-spacing:1px">VERSION 1.2 - ZTP</div>
    <div style="overflow-y:auto;flex:1">{% for row in history %}<div class="h-item" onclick="document.getElementById('inp').value='{{row[0]|replace("'","\\'")}}';document.getElementById('inp').focus()"><span class="h-text">💬 {{row[0]}}</span><a href="/del/{{row[2]}}" class="del-btn">×</a></div>{% endfor %}</div></div>
    <div class="main"><div class="header"><div><span style="cursor:pointer;margin-right:15px" onclick="toggleSidebar()">☰</span><b>NTI Zero-Touch</b></div><a href="/clear" style="text-decoration:none;color:#007bff;font-size:12px;border:1px solid;padding:4px 10px;border-radius:15px">+ New Chat</a></div>
    <div class="chat-area" id="c">{% for row in history %}<div class="m u">{{row[0]}}</div><div class="m a">{{row[1]}}</div>{% endfor %}</div>
    <div class="input-wrap"><form method="POST" id="chat-form"><textarea name="msg" placeholder="Describe migration task..." required id="inp"></textarea>
    <div class="btn-wrap"><button style="border:none;background:none;color:#007bff;cursor:pointer;font-size:20px">➤</button></div></form></div>
    </div><script>
      document.getElementById('c').scrollTop=999999;
      function toggleSidebar() {
          const sb = document.getElementById('sb');
          sb.classList.toggle('hide');
          localStorage.setItem('sb_state', sb.classList.contains('hide') ? 'hidden' : 'visible');
      }
      if(localStorage.getItem('sb_state') === 'hidden') document.getElementById('sb').classList.add('hide');
      document.getElementById('inp').addEventListener('keydown', function(e) {
          if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              document.getElementById('chat-form').submit();
          }
      });
    </script></body></html>""", history=h)

    @app.route("/del/<int:cid>")
    def del_chat(cid):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("DELETE FROM chat_history WHERE id=%s",(cid,));conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))

    @app.route("/clear")
    def clear():
      return redirect(url_for('chat'))

    if __name__ == "__main__":
      app.run(host="0.0.0.0", port=5000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-client
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-client
  template:
    metadata:
      labels:
        app: gpt-client
    spec:
      containers:
      - name: gpt-client
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install flask openai psycopg2-binary;
            python /app/app.py;
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nti-gpt-secrets
              key: OPENAI_API_KEY
        - name: AWX_TOKEN
          valueFrom:
            secretKeyRef:
              name: nti-gpt-secrets
              key: AWX_TOKEN
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        configMap:
          name: gpt-app-code
