---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request
    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", os.getenv("AWX_TOKEN"), "11"
    
    def trig(m, d=False):
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}"); req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req) as r: return json.loads(r.read().decode()).get('job')
      except Exception as e: return f"ERR: {e}"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        cp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "NTI GPT-5 Provisioner. YAML ONLY for changes. No text before/after YAML."}, {"role": "user", "content": m}])
        r = cp.choices[0].message.content
        if "kind:" in r:
            # CLEANER: Remove markdown and trailing text
            c_r = r.replace("```yaml", "").replace("```", "").strip()
            # Stop parsing if GPT adds a summary after the YAML
            if "apiVersion" in c_r:
                is_d = any(w in m.lower() for w in ["delete", "remove", "wipe"])
                j = trig(c_r, is_d); f = r + f"\n\n🚀 GPT-5 JOB: {j}"
        else: f = r
        db_save(m, f); return redirect(url_for('chat'))
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("SELECT u_in, g_out FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif;margin:0;display:flex;height:100vh;background:#f4f7f6;overflow:hidden}
    #sb{width:260px;background:#202123;color:#fff;display:flex;flex-direction:column;transition:0.3s}
    #sb.hide{width:0;padding:0;overflow:hidden}
    .main{flex:1;display:flex;flex-direction:column;position:relative;background:#fff}
    .header{padding:12px 20px;border-bottom:1px solid #eee;display:flex;justify-content:space-between;align-items:center;background:#fff}
    .chat-area{flex:1;overflow-y:auto;padding:20px 15%;display:flex;flex-direction:column;gap:15px}
    .m{padding:12px 18px;border-radius:15px;max-width:85%;white-space:pre-wrap;font-size:14px;line-height:1.4;box-shadow:0 1px 2px rgba(0,0,0,0.1)}
    .u{align-self:flex-end;background:#007bff;color:#fff;border-bottom-right-radius:2px}
    .a{align-self:flex-start;background:#f7f7f8;color:#333;border:1px solid #ddd;border-bottom-left-radius:2px;font-family:monospace}
    .input-wrap{padding:20px 15%;background:#fff}
    form{display:flex;border:1px solid #ddd;border-radius:24px;padding:5px 15px;background:#fff}
    input{flex:1;border:none;outline:none;padding:10px;font-size:15px}
    .new-chat{text-decoration:none;color:#007bff;border:1px solid #007bff;padding:5px 15px;border-radius:20px;font-size:12px;font-weight:bold}
    .btn-t{cursor:pointer;font-size:20px;margin-right:10px;color:#666}
    </style></head><body>
    <div id="sb"><div style="padding:20px;font-size:11px;opacity:0.5;letter-spacing:1px">DEMO HISTORY</div>
    <div style="overflow-y:auto;flex:1">{% for row in history %}<div style="padding:10px 20px;font-size:12px;opacity:0.8;border-bottom:1px solid #333">💬 {{row[0][:25]}}</div>{% endfor %}</div></div>
    <div class="main">
      <div class="header"><div><span class="btn-t" onclick="document.getElementById('sb').classList.toggle('hide')">☰</span><b>NTI Zero-Touch (GPT-5 Mode)</b></div>
      <a href="/clear" class="new-chat">+ New Chat</a></div>
      <div class="chat-area" id="c">{% for row in history %}<div class="m u">{{row[0]}}</div><div class="m a">{{row[1]}}</div>{% endfor %}</div>
      <div class="input-wrap"><form method="POST"><input type="text" name="msg" placeholder="Ask or Deploy..." required autocomplete="off">
      <button style="border:none;background:none;color:#007bff;font-size:20px;cursor:pointer">➤</button></form></div>
    </div><script>document.getElementById('c').scrollTop=999999;</script></body></html>""", history=h)

    @app.route("/clear")
    def clear():
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("DELETE FROM chat_history;");conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))
    if __name__ == "__main__":
      app.run(host="0.0.0.0", port=5000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-client
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-client
  template:
    metadata:
      labels:
        app: gpt-client
    spec:
      containers:
      - name: gpt-client
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install flask openai psycopg2-binary;
            python /app/app.py;
        env:
        - name: OPENAI_API_KEY
          value: "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"
        - name: AWX_TOKEN
          value: "x645j8MA4YzR7cfISWW4yF17By2c8o"
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        configMap:
          name: gpt-app-code
