apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2, re
    from urllib import request as url_request
    app = Flask(__name__)
    
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", os.getenv("AWX_TOKEN"), "11"
    
    def trig(r, d=False):
      # Extract the YAML start point
      start = r.find("apiVersion:")
      if start == -1: 
          print("DEBUG: No apiVersion found in response")
          return "NO-YAML"
      
      m = r[start:].strip()
      m = re.sub(r"```yaml|```", "", m).strip()
      
      # Prepare the AWX payload
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}")
      req.add_header("Content-Type", "application/json")
      
      try:
        print(f"DEBUG: Attempting to trigger AWX Job {ID}...")
        with url_request.urlopen(req, timeout=10) as resp:
            job_id = json.loads(resp.read().decode()).get('job')
            print(f"DEBUG: AWX Success! Job ID: {job_id}")
            return job_id
      except Exception as e:
        print(f"DEBUG: AWX ERROR: {e}")
        return f"AWX-ERR: {e}"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        cp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "You are a K8s YAML generator. Only output valid YAML."}, {"role": "user", "content": m}])
        r = cp.choices[0].message.content
        res = trig(r, 'delete' in m.lower())
        f = r + f"\n\n🚀 JOB: {res}"
        db_save(m, f); return redirect(url_for('chat'))
      
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("SELECT u_in, g_out, id FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif;margin:0;display:flex;height:100vh;background:#f4f7f6;overflow:hidden}
    #sb{width:280px;background:#202123;color:#fff;display:flex;flex-direction:column;flex-shrink:0;transition:0.3s}
    #sb.hide{width:0;overflow:hidden}
    .main{flex:1;display:flex;flex-direction:column;background:#fff}
    .header{padding:12px 20px;border-bottom:1px solid #eee;display:flex;justify-content:space-between;align-items:center}
    .chat-area{flex:1;overflow-y:auto;padding:20px 15%;display:flex;flex-direction:column;gap:15px}
    .m{padding:12px 18px;border-radius:15px;max-width:85%;white-space:pre-wrap;font-size:14px;line-height:1.4}
    .u{align-self:flex-end;background:#007bff;color:#fff}
    .a{align-self:flex-start;background:#f7f7f8;border:
