---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request
    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", "PASTE_YOUR_TOKEN_HERE", "11"
    
    def trig(m, d=False):
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}"); req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req) as r: return json.loads(r.read().decode()).get('job')
      except Exception as e: return f"ERR:{e}"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("CREATE TABLE IF NOT EXISTS chat_history (id SERIAL PRIMARY KEY, u_in TEXT, g_out TEXT);")
        cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        cp = client.chat.completions.create(
          model="gpt-4o", 
          messages=[{
            "role": "system", 
            "content": "You are the NTI Zero-Touch Provisioner. If the user wants to deploy/delete/scale, output ONLY YAML. If they ask a question or for information, answer normally without YAML. Never use the word Architect."
          }, {"role": "user", "content": m}]
        )
        r = cp.choices[0].message.content
        
        # LOGIC: Only trigger AWX if YAML keywords are found
        if "kind:" in r and "metadata:" in r:
            is_d = any(w in m.lower() for w in ["delete", "remove", "wipe", "destroy"])
            j = trig(r, is_d)
            f = r + f"\n\n{'🗑️ DELETED' if is_d else '🚀 DEPLOYED'} | Job: {j}"
        else:
            f = r # Pure conversation, no job triggered
            
        db_save(m, f); return redirect(url_for('chat'))
      
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("SELECT u_in, g_out FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:-apple-system,sans-serif;background:#fff;margin:0;display:flex;height:100vh;overflow:hidden}
    #sb{width:260px;background:#202123;color:#fff;display:flex;flex-direction:column;transition:0.3s;overflow:hidden}
    #sb.hide{width:0;padding:0}
    .main{flex:1;display:flex;flex-direction:column;background:#fff;position:relative}
    .header{padding:10px 20px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between;background:#fff;z-index:10}
    .header-left{display:flex;align-items:center;gap:15px}
    .toggle-btn{cursor:pointer;font-size:20px;color:#666}
    .new-chat-btn{text-decoration:none;color:#007bff;border:1px solid #007bff;padding:6px 15px;border-radius:18px;font-size:13px;font-weight:600;transition:0.2s}
    .new-chat-btn:hover{background:#007bff;color:#fff}
    .chat-area{flex:1;overflow-y:auto;padding:20px 15% 100px 15%;display:flex;flex-direction:column;gap:20px}
    .m{max-width:85%;padding:15px 20px;border-radius:15px;font-size:15px;line-height:1.5;white-space:pre-wrap}
    .u{align-self:flex-end;background:#007bff;color
