---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request
    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", "PASTE_YOUR_TOKEN_HERE", "11"
    
    def trig(m, d=False):
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}"); req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req) as r: return json.loads(r.read().decode()).get('job')
      except Exception as e: return f"ERR:{e}"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("CREATE TABLE IF NOT EXISTS chat_history (id SERIAL PRIMARY KEY, u_in TEXT, g_out TEXT);")
        cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        is_d = any(w in m.lower() for w in ["delete", "remove", "wipe", "destroy"])
        cp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "Helpful Kubernetes Provisioner. YAML ONLY. No architect/strategist talk."}, {"role": "user", "content": m}])
        r = cp.choices[0].message.content; j = trig(r, is_d)
        f = r + f"\n\n{'🗑️ DELETED' if is_d else '🚀 DEPLOYED'} | Job: {j}"
        db_save(m, f); return redirect(url_for('chat'))
      
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("SELECT u_in, g_out FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass

      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:-apple-system,sans-serif;background:#fff;margin:0;display:flex;height:100vh;overflow:hidden}
    .sidebar{width:260px;background:#202123;color:#fff;display:flex;flex-direction:column;padding:10px}
    .new-chat{border:1px solid #4d4d4f;padding:12px;border-radius:5px;cursor:pointer;text-align:left;background:none;color:#fff;margin-bottom:20px;display:flex;align-items:center;gap:10px}
    .history-item{padding:10px;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#ececf1;border-radius:5px;margin-bottom:5px;cursor:default}
    .main{flex:1;display:flex;flex-direction:column;position:relative;background:#fff}
    .chat-area{flex:1;overflow-y:auto;padding:40px 15% 100px 15%;display:flex;flex-direction:column;gap:20px}
    .m{max-width:85%;padding:15px 20px;border-radius:15px;font-size:15px;line-height:1.5;white-space:pre-wrap}
    .u{align-self:flex-end;background:#007bff;color:#fff;border-bottom-right-radius:4px}
    .a{align-self:flex-start;background:#f7f7f8;color:#333;border:1px solid #e5e5e5;border-bottom-left-radius:4px;font-family:monospace;font-size:13px}
    .input-wrap{position:absolute;bottom:0;left:0;right:0;padding:20px 15%;background:linear-gradient(transparent,#fff 20%)}
    form{display:flex;background:#fff;border:1px solid #ddd;border-radius:10px;padding:10px;box-shadow:0 0 15px rgba(0,0,0,0.05)}
    input{flex:1;border:none;outline:none;padding:10px;font-size:16px}
    button.send{background:#007bff;color:#fff;border:none;padding:8px 15px;border-radius:5px;cursor:pointer;font-weight:bold}
    a{text-decoration:none;color:inherit}
    </style></head><body>
    <div class="sidebar">
      <a href="/clear" class="new-chat"><span>+</span> New Chat</a>
      <div style="overflow-y:auto;flex:1">
        {% for row in history %}
          <div class="history-item">💬 {{row[0][:30]}}...</div>
        {% endfor %}
      </div>
    </div>
    <div class="main">
      <div class="chat-area" id="c">
        {% for row in history %}
          <div class="m u">{{row[0]}}</div>
          <div class="m a">{{row[1]}}</div>
        {% endfor %}
      </div>
      <div class="input-wrap">
        <form method="POST"><input type="text" name="msg" placeholder="What can I deploy for you?" required autofocus>
        <button type="submit" class="send">Send</button></form>
      </div>
    </div>
    <script>const c=document.getElementById('c');c.scrollTop=c.scrollHeight;</script>
    </body></html>""", history=h)

    @app.route("/clear")
    def clear():
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("DELETE FROM chat_history;");conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))

    if __name__ == "__main__":
      app.run(host="0.0.0.0", port=5000)
