---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, requests, psycopg2

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    # --- ZERO TOUCH CONFIGURATION ---
    AWX_URL = "http://awx-demo-service.awx.svc.cluster.local" # Update if your service name is different
    AWX_TOKEN = "x645j8MA4YzR7cfISWW4yF17By2c8o"
    TEMPLATE_ID = "11" 
    # --------------------------------

    def trigger_awx(manifest_content):
        url = f"{AWX_URL}/api/v2/job_templates/{TEMPLATE_ID}/launch/"
        headers = {"Authorization": f"Bearer {AWX_TOKEN}", "Content-Type": "application/json"}
        payload = {"extra_vars": {"manifest_content": manifest_content}}
        r = requests.post(url, headers=headers, json=payload, verify=False)
        return r.json().get('job')

    def save_to_db(user_msg, gpt_resp):
        conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
        cur = conn.cursor()
        cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (user_msg, gpt_resp))
        conn.commit()
        cur.close(); conn.close()

    @app.route("/", methods=["GET", "POST"])
    def chat():
        if request.method == "POST":
            user_msg = request.form.get("msg")
            
            # 1. Get the Blueprint from GPT
            completion = client.chat.completions.create(
                model="gpt-5-mini", 
                messages=[{"role": "system", "content": "You are a Kubernetes Architect. Output ONLY valid YAML manifests."},
                          {"role": "user", "content": user_msg}]
            )
            gpt_resp = completion.choices[0].message.content
            
            # 2. Trigger the "Muscle" (AWX) if it's a deployment request
            job_id = None
            if any(word in user_msg.lower() for word in ["deploy", "provision", "create", "build"]):
                job_id = trigger_awx(gpt_resp)
            
            final_resp = gpt_resp
            if job_id:
                final_resp += f"\n\n🚀 **DEPLOYMENT TRIGGERED!**\nAWX Job ID: {job_id}"
            
            save_to_db(user_msg, final_resp)
            return redirect(url_for('chat'))
        
        # (Fetch history logic remains the same...)
        conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
        cur = conn.cursor(); cur.execute("SELECT user_input, gpt_output FROM chat_history ORDER BY created_at ASC;"); history = cur.fetchall(); cur.close(); conn.close()
        return render_template_string(open('index.html').read(), history=history) # Note: assumes HTML is in a separate file or string

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
