---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request
    app = Flask(__name__)
    
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", os.getenv("AWX_TOKEN"), "11"
    
    def trig(m, d=False):
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}"); req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req) as r: return json.loads(r.read().decode()).get('job')
      except: return "AWX-ERR"
    
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        cp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "NTI GPT-5 Provisioner. YAML ONLY."}, {"role": "user", "content": m}])
        r = cp.choices[0].message.content
        f = r + (f"\n\n🚀 GPT-5 JOB: {trig(r)}" if "kind:" in r else "")
        db_save(m, f); return redirect(url_for('chat'))
      
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("SELECT u_in, g_out, id FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif;margin:0;display:flex;height:100vh;background:#f4f7f6;overflow:hidden}
    #sb{width:280px;background:#202123;color:#fff;display:flex;flex-direction:column;transition:0.3s;flex-shrink:0}
    #sb.hide{width:0;padding:0;overflow:hidden}
    .main{flex:1;display:flex;flex-direction:column;background:#fff}
    .header{padding:12px 20px;border-bottom:1px solid #eee;display:flex;justify-content:space-between;align-items:center}
    .chat-area{flex:1;overflow-y:auto;padding:20px 15%;display:flex;flex-direction:column;gap:15px}
    .m{padding:12px 18px;border-radius:15px;max-width:85%;white-space:pre-wrap;font-size:14px;line-height:1.4;box-shadow:0 1px 2px rgba(0,0,0,0.1)}
    .u{align-self:flex-end;background:#007bff;color:#fff}
    .a{align-self:flex-start;background:#f7f7f8;border:1px solid #ddd;font-family:monospace}
    .input-wrap{padding:20px 15%}
    form{display:flex;border:1px solid #ddd;border-radius:24px;padding:5px 15px}
    input{flex:1;border:none;outline:none;padding:10px;font-size:15px}
    .h-item{padding:12px 20px;font-size:12px;border-bottom:1px solid #333;display:flex;justify-content:space-between;align-items:center;cursor:pointer}
    .h-item:hover{background:#2a2b32}
    .h-text{flex:1;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;margin-right:10px}
    .del-btn{color:#ff4d4d;text-decoration:none;font-weight:bold;padding:5px;opacity:0.6}
    .del-btn:hover{opacity:1}
    .new-chat{text-decoration:none;color:#007bff;border:1px solid #007bff;padding:5px 15px;border-radius:20px;font-size:12px;font-weight:bold}
    .btn-t{cursor:pointer;font-size:20px;margin-right:15px;color:#666}
    </style></head><body>
    <div id="sb">
      <div style="padding:20px;font-size:11px;opacity:0.5;font-weight:bold">CHRONICLE (GPT-5)</div>
      <div style="overflow-y:auto;flex:1">
        {% for row in history %}
          <div class="h-item" onclick="loadMsg('{{row[0]|replace("'", "\\'")}}')">
            <span class="h-text">💬 {{row[0]}}</span>
            <a href="/del/{{row[2]}}" class="del-btn" onclick="event.stopPropagation()">×</a>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="main">
      <div class="header">
        <div><span class="btn-t" onclick="document.getElementById('sb').classList.toggle('hide')">☰</span><b>NTI Zero-Touch (GPT-5)</b></div>
        <a href="/clear" class="new-chat">+ New Chat</a>
      </div>
      <div class="chat-area" id="c">
        {% for row in history %}<div class="m u">{{row[0]}}</div><div class="m a">{{row[1]}}</div>{% endfor %}
      </div>
      <div class="input-wrap">
        <form method="POST"><input type="text" name="msg" placeholder="Ask GPT-5..." required id="inp" autocomplete="off">
        <button style="border:none;background:none;color:#007bff;cursor:pointer;font-size:20px">➤</button></form>
      </div>
    </div>
    <script>
      function loadMsg(t){ document.getElementById('inp').value = t; document.getElementById('inp').focus(); }
      document.getElementById('c').scrollTop=999999;
    </script>
    </body></html>""", history=h)

    @app.route("/del/<int:cid>")
    def del_chat(cid):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("DELETE FROM chat_history WHERE id=%s",(cid,));conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))

    @app.route("/clear")
    def clear():
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword")
        cur=conn.cursor();cur.execute("DELETE FROM chat_history;");conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))
    if __name__ == "__main__":
      app.run(host="0.0.0.0", port=5000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-client
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-client
  template:
    metadata:
      labels:
        app: gpt-client
    spec:
      containers:
      - name: gpt-client
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install flask openai psycopg2-binary;
            python /app/app.py;
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nti-gpt-secrets
              key: OPENAI_API_KEY
        - name: AWX_TOKEN
          valueFrom:
            secretKeyRef:
              name: nti-gpt-secrets
              key: AWX_TOKEN
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        configMap:
          name: gpt-app-code
