---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request, parse, error as url_error

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    AWX_URL = "http://awx-service.awx.svc.cluster.local" 
    AWX_TOKEN = "x645j8MA4YzR7cfISWW4yF17By2c8o"
    TEMPLATE_ID = "11" 

    def trigger_awx(manifest_content):
        url = f"{AWX_URL}/api/v2/job_templates/{TEMPLATE_ID}/launch/"
        data = json.dumps({"extra_vars": {"manifest_content": manifest_content}}).encode('utf-8')
        req = url_request.Request(url, data=data, method='POST')
        req.add_header("Authorization", f"Bearer {AWX_TOKEN}")
        req.add_header("Content-Type", "application/json")
        try:
            with url_request.urlopen(req) as response:
                return json.loads(response.read().decode()).get('job')
        except Exception as e:
            return f"ERROR: {str(e)}"

    def save_to_db(user_msg, gpt_resp):
        try:
            conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
            cur = conn.cursor()
            cur.execute("CREATE TABLE IF NOT EXISTS chat_history (id SERIAL PRIMARY KEY, user_input TEXT, gpt_output TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);")
            cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (user_msg, gpt_resp))
            conn.commit()
            cur.close(); conn.close()
        except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
        if request.method == "POST":
            user_msg = request.form.get("msg")
            completion = client.chat.completions.create(
                model="gpt-4o", 
                messages=[{"role": "system", "content": "You are a Kubernetes Architect. Output ONLY valid YAML manifests."},
                          {"role": "user", "content": user_msg}]
            )
            gpt_resp = completion.choices[0].message.content
            job_id = trigger_awx(gpt_resp) if any(w in user_msg.lower() for w in ["deploy", "provision", "create", "build"]) else None
            final_resp = gpt_resp + (f"\n\n🚀 DEPLOYMENT TRIGGERED! ID: {job_id}" if job_id else "")
            save_to_db(user_msg, final_resp)
            return redirect(url_for('chat'))
        
        try:
            conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
            cur = conn.cursor(); cur.execute("SELECT user_input, gpt_output FROM chat_history ORDER BY created_at ASC;"); history = cur.fetchall(); cur.close(); conn.close()
        except: history = []

        return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif; background:#f4f7f6; padding:20px;}
    .msg{background:white; padding:15px; border-radius:10px; margin-bottom:10px; border:1px solid #ddd; white-space:pre-wrap;}
    .user{color:blue; font-weight:bold;}
    </style></head><body>
    <h2>Zero Touch Labs</h2>
    {% for c in history %}
    <div class="msg"><span class="user">User:</span> {{c[0]}}</div>
    <div class="msg"><b>AI:</b> {{c[1]}}</div>
    {% endfor %}
    <form method="POST"><input type="text" name="msg" style="width:80%" autofocus> <button>Send</button></form>
    </body></html>""", history=history)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
