---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os
    import psycopg2

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def get_db_connection():
        return psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")

    def save_to_db(user_msg, gpt_resp):
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (user_msg, gpt_resp))
        conn.commit()
        cur.close()
        conn.close()

    def fetch_full_history():
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            # Get the history in ascending order to show the "thread"
            cur.execute("SELECT user_input, gpt_output, created_at FROM chat_history ORDER BY created_at ASC;")
            rows = cur.fetchall()
            cur.close()
            conn.close()
            return rows
        except:
            return []

    HTML = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Zero Touch Provisioning</title>
        <style>
            body { font-family: 'Segoe UI', sans-serif; background: #f4f7f6; margin: 0; display: flex; flex-direction: column; height: 100vh; }
            header { background: #fff; padding: 15px 40px; border-bottom: 1px solid #ddd; display: flex; justify-content: space-between; align-items: center; }
            
            .chat-container { flex: 1; overflow-y: auto; padding: 20px 10% 100px 10%; display: flex; flex-direction: column; gap: 20px; }
            
            /* Message Bubbles */
            .msg-group { display: flex; flex-direction: column; width: 100%; }
            .user-msg { align-self: flex-end; background: #007bff; color: white; padding: 12px 18px; border-radius: 15px 15px 2px 15px; max-width: 70%; font-size: 15px; margin-bottom: 5px; }
            .gpt-msg { align-self: flex-start; background: white; border: 1px solid #e0e0e0; padding: 15px 20px; border-radius: 15px 15px 15px 2px; max-width: 85%; font-size: 15px; line-height: 1.6; white-space: pre-wrap; }
            
            pre { background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1px solid #eee; overflow-x: auto; font-family: monospace; }

            /* Fixed Footer Input */
            .footer-input { position: fixed; bottom: 0; width: 100%; background: white; border-top: 1px solid #ddd; padding: 20px 0; }
            .input-wrap { max-width: 80%; margin: auto; display: flex; gap: 10px; }
            input[type="text"] { flex: 1; padding: 14px; border: 1px solid #ccc; border-radius: 8px; outline: none; font-size: 16px; }
            button { background: #222; color: white; border: none; padding: 0 25px; border-radius: 8px; cursor: pointer; font-weight: bold; }
            .new-chat-btn { background: #f0f0f0; color: #666; font-size: 12px; padding: 8px 15px; text-decoration: none; border-radius: 5px; border: 1px solid #ddd; }
        </style>
    </head>
    <body>
        <header>
            <h1>Zero Touch Provisioning</h1>
            <a href="/clear" class="new-chat-btn">+ New Chat</a>
        </header>

        <div class="chat-container" id="chatBox">
            {% for chat in history %}
            <div class="msg-group">
                <div class="user-msg">{{ chat[0] }}</div>
                <div class="gpt-msg">{{ chat[1] }}</div>
            </div>
            {% endfor %}
        </div>

        <div class="footer-input">
            <form method="POST" class="input-wrap">
                <input type="text" name="msg" placeholder="Command the infrastructure..." required autofocus autocomplete="off">
                <button type="submit">Execute</button>
            </form>
        </div>

        <script>
            var objDiv = document.getElementById("chatBox");
            objDiv.scrollTop = objDiv.scrollHeight;
        </script>
    </body>
    </html>
    """

    @app.route("/", methods=["GET", "POST"])
    def chat():
        if request.method == "POST":
            user_msg = request.form.get("msg")
            completion = client.chat.completions.create(model="gpt-5-mini", messages=[{"role": "user", "content": user_msg}])
            gpt_resp = completion.choices[0].message.content
            save_to_db(user_msg, gpt_resp)
            return redirect(url_for('chat')) # Redirect to refresh and show new message
        
        history = fetch_full_history()
        return render_template_string(HTML, history=history)

    @app.route("/clear")
    def clear():
        # This effectively 'resets' the view for a New Chat
        # In a production app, we'd use session IDs, but for this lab, we'll just clear the table
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("DELETE FROM chat_history;")
        conn.commit()
        cur.close()
        conn.close()
        return redirect(url_for('chat'))

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
