---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string
    from openai import OpenAI
    import os
    import psycopg2

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def save_to_db(user_msg, gpt_resp):
        try:
            conn = psycopg2.connect(
                host="postgres",
                database="appdb",
                user="appuser",
                password="supersecretpassword"
            )
            cur = conn.cursor()
            cur.execute("""
                CREATE TABLE IF NOT EXISTS chat_history (
                    id SERIAL PRIMARY KEY, 
                    user_input TEXT, 
                    gpt_output TEXT, 
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (user_msg, gpt_resp))
            conn.commit()
            cur.close()
            conn.close()
        except Exception as e:
            print(f"Database error: {e}")

    HTML = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>NTI No Touch Provisioning</title>
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 40px; background-color: #ffffff; color: #000000; }
            .container { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #000; border-radius: 0px; }
            h1 { color: #000000; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #000; padding-bottom: 10px; }
            input[type="text"] { width: 75%; padding: 12px; border: 1px solid #000; border-radius: 0px; font-size: 16px; }
            button { padding: 12px 25px; background-color: #000000; color: #ffffff; border: none; border-radius: 0px; cursor: pointer; font-weight: bold; text-transform: uppercase; }
            button:hover { background-color: #333333; }
            .chat-box { margin-top: 30px; padding: 20px; border: 1px solid #000; background: #fafafa; }
            .footer { margin-top: 20px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>NTI No Touch Provisioning</h1>
            <p style="font-weight: bold;">Automated AI-Driven Infrastructure Lab</p>
            <form method="POST">
                <input type="text" name="msg" placeholder="SYSTEM COMMAND..." required>
                <button type="submit">Execute</button>
            </form>
            {% if resp %}
                <div class="chat-box">
                    <strong style="text-transform: uppercase;">GPT Response:</strong><br><br>
                    {{ resp }}
                </div>
                <div class="footer">LOGGED TO POSTGRES_DB // STATUS: SECURE</div>
            {% endif %}
        </div>
    </body>
    </html>
    """

    @app.route("/", methods=["GET", "POST"])
    def chat():
        resp = None
        if request.method == "POST":
            user_msg = request.form.get("msg")
            completion = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": user_msg}]
            )
            resp = completion.choices[0].message.content
            save_to_db(user_msg, resp)
        return render_template_string(HTML, resp=resp)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-client
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-client
  template:
    metadata:
      labels:
        app: gpt-client
    spec:
      containers:
      - name: python-app
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for configmap mount..."
            sleep 5
            ls -R /app
            pip install flask openai psycopg2-binary
            python /app/app.py
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gpt-secret
              key: api-key
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: code-volume
          mountPath: /app
      volumes:
      - name: code-volume
        configMap:
          name: gpt-app-code
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-service
  namespace: demo-webdb
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 5000
  selector:
    app: gpt-client
