---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string
    from openai import OpenAI
    import os
    import psycopg2
    from datetime import datetime

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def get_db_connection():
        return psycopg2.connect(
            host="postgres",
            database="appdb",
            user="appuser",
            password="supersecretpassword"
        )

    def save_to_db(user_msg, gpt_resp):
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("""
                CREATE TABLE IF NOT EXISTS chat_history (
                    id SERIAL PRIMARY KEY, 
                    user_input TEXT, 
                    gpt_output TEXT, 
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (user_msg, gpt_resp))
            conn.commit()
            cur.close()
            conn.close()
        except Exception as e:
            print(f"Database error: {e}")

    def fetch_history():
        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("SELECT user_input, gpt_output, created_at FROM chat_history ORDER BY created_at DESC LIMIT 15;")
            rows = cur.fetchall()
            cur.close()
            conn.close()
            return rows
        except:
            return []

    HTML = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>NTI No Touch Provisioning</title>
        <style>
            :root { --bg: #f5f7fb; --sidebar: #ffffff; --text: #333; --accent: #4a90e2; --border: #e1e4e8; }
            body { font-family: 'Inter', -apple-system, sans-serif; background: var(--bg); color: var(--text); margin: 0; display: flex; height: 100vh; }
            
            /* Sidebar */
            .sidebar { width: 280px; background: var(--sidebar); border-right: 1px solid var(--border); display: flex; flex-direction: column; }
            .sidebar-header { padding: 25px; font-weight: 700; font-size: 14px; text-transform: uppercase; color: #888; border-bottom: 1px solid var(--border); }
            .history-list { flex: 1; overflow-y: auto; padding: 10px; }
            .history-item { padding: 12px; border-radius: 8px; margin-bottom: 5px; font-size: 13px; color: #555; cursor: pointer; transition: background 0.2s; }
            .history-item:hover { background: #f0f2f5; }
            .history-item small { display: block; color: #bbb; font-size: 10px; margin-bottom: 3px; }

            /* Main Area */
            .main { flex: 1; display: flex; flex-direction: column; }
            .top-bar { padding: 15px 40px; background: #fff; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; }
            .top-bar h1 { font-size: 18px; margin: 0; color: #222; }
            
            .chat-window { flex: 1; overflow-y: auto; padding: 40px; display: flex; flex-direction: column; gap: 20px; }
            
            .bubble { max-width: 80%; padding: 15px 20px; border-radius: 18px; line-height: 1.5; font-size: 15px; }
            .user-bubble { align-self: flex-end; background: var(--accent); color: white; border-bottom-right-radius: 4px; }
            .gpt-bubble { align-self: flex-start; background: white; color: #222; border: 1px solid var(--border); border-bottom-left-radius: 4px; white-space: pre-wrap; font-family: inherit; }
            
            /* Code formatting inside bubbles */
            code, pre { background: #f8f9fa; padding: 10px; border-radius: 5px; font-family: 'Consolas', monospace; font-size: 14px; display: block; overflow-x: auto; margin-top: 10px; }

            /* Input */
            .input-container { padding: 20px 40px; background: #fff; border-top: 1px solid var(--border); }
            form { display: flex; gap: 10px; }
            input[type="text"] { flex: 1; padding: 15px; border: 1px solid var(--border); border-radius: 10px; outline: none; font-size: 15px; }
            input[type="text"]:focus { border-color: var(--accent); }
            button { background: var(--accent); color: white; border: none; padding: 0 25px; border-radius: 10px; font-weight: 600; cursor: pointer; }
            button:hover { background: #357abd; }
        </style>
    </head>
    <body>
        <div class="sidebar">
            <div class="sidebar-header">Recent Activity</div>
            <div class="history-list">
                {% for row in history %}
                <div class="history-item">
                    <small>{{ row[2].strftime('%b %d, %H:%M') }}</small>
                    {{ row[0][:50] }}{% if row[0]|length > 50 %}...{% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="main">
            <div class="top-bar">
                <h1>NTI No Touch Provisioning</h1>
                <div style="font-size: 12px; color: #999;">Engine: GPT-5-MINI</div>
            </div>

            <div class="chat-window" id="chatWindow">
                {% if last_user %}
                    <div class="bubble user-bubble">{{ last_user }}</div>
                    <div class="bubble gpt-bubble">{{ last_resp }}</div>
                {% else %}
                    <div style="text-align: center; color: #aaa; margin-top: 100px;">Enter a command below to begin provisioning.</div>
                {% endif %}
            </div>

            <div class="input-container">
                <form method="POST">
                    <input type="text" name="msg" placeholder="Type your instruction..." autofocus required>
                    <button type="submit">Send</button>
                </form>
            </div>
        </div>

        <script>
            const win = document.getElementById("chatWindow");
            win.scrollTop = win.scrollHeight;
        </script>
    </body>
    </html>
    """

    @app.route("/", methods=["GET", "POST"])
    def chat():
        last_user = None
        last_resp = None
        if request.method == "POST":
            user_msg = request.form.get("msg")
            completion = client.chat.completions.create(
                model="gpt-5-mini",
                messages=[{"role": "user", "content": user_msg}]
            )
            last_resp = completion.choices[0].message.content
            last_user = user_msg
            save_to_db(user_msg, last_resp)
        
        history = fetch_history()
        return render_template_string(HTML, history=history, last_user=last_user, last_resp=last_resp)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
---
# Deployment and Service sections remain the same
