---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request, parse, error as url_error

    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    AWX_URL = "http://awx-service.awx.svc.cluster.local" 
    AWX_TOKEN = "PASTE_YOUR_TOKEN_HERE" 
    TEMPLATE_ID = "11" 

    def trigger_awx(manifest_content, delete_mode=False):
        url = f"{AWX_URL}/api/v2/job_templates/{TEMPLATE_ID}/launch/"
        payload = {"extra_vars": {"manifest_content": manifest_content, "DELETE_MODE": "true" if delete_mode else "false"}}
        data = json.dumps(payload).encode('utf-8')
        req = url_request.Request(url, data=data, method='POST')
        req.add_header("Authorization", f"Bearer {AWX_TOKEN}")
        req.add_header("Content-Type", "application/json")
        try:
            with url_request.urlopen(req) as response:
                return json.loads(response.read().decode()).get('job')
        except Exception as e: return f"ERR: {str(e)}"

    def save_to_db(u, g):
        try:
            conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
            cur = conn.cursor()
            cur.execute("CREATE TABLE IF NOT EXISTS chat_history (id SERIAL PRIMARY KEY, user_input TEXT, gpt_output TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);")
            cur.execute("INSERT INTO chat_history (user_input, gpt_output) VALUES (%s, %s)", (u, g))
            conn.commit(); cur.close(); conn.close()
        except: pass

    @app.route("/", methods=["GET", "POST"])
    def chat():
        if request.method == "POST":
            user_msg = request.form.get("msg")
            is_del = request.form.get("action") == "delete"
            comp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "K8s Architect. YAML ONLY."}, {"role": "user", "content": user_msg}])
            gpt_resp = comp.choices[0].message.content
            job_id = trigger_awx(gpt_resp, delete_mode=is_del)
            final_resp = gpt_resp + f"\n\n{'🗑️' if is_del else '🚀'} ID: {job_id}"
            save_to_db(user_msg, final_resp)
            return redirect(url_for('chat'))
        try:
            conn = psycopg2.connect(host="postgres", database="appdb", user="appuser", password="supersecretpassword")
            cur = conn.cursor(); cur.execute("SELECT user_input, gpt_output FROM chat_history ORDER BY created_at ASC;"); history = cur.fetchall(); cur.close(); conn.close()
        except: history = []
        return render_template_string("""
    <!DOCTYPE html><html><body style="font-family:sans-serif;padding:20px;background:#eee">
    <h2>NTI Zero-Touch</h2>
    {% for c in history %}<div style="background:white;padding:10px;margin-bottom:5px;border-radius:5px"><b>User:</b> {{c[0]}}<br><b>AI:</b><pre>{{c[1]}}</pre></div>{% endfor %}
    <form method="POST"><input type="text" name="msg" style="width:70%" required autofocus>
    <button name="action" value="deploy" style="background:green;color:white">Deploy</button>
    <button name="action" value="delete" style="background:red;color:white">Delete</button></form>
    </body></html>""", history=history)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
