---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-app-code
  namespace: demo-webdb
data:
  app.py: |
    from flask import Flask, request, render_template_string, redirect, url_for
    from openai import OpenAI
    import os, json, psycopg2
    from urllib import request as url_request
    app = Flask(__name__)
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    U, T, ID = "http://awx-service.awx.svc.cluster.local", "x645j8MA4YzR7cfISWW4yF17By2c8o", "11"
    def trig(m, d=False):
      p = {"extra_vars": {"manifest_content": m, "DELETE_MODE": "true" if d else "false"}}
      req = url_request.Request(f"{U}/api/v2/job_templates/{ID}/launch/", data=json.dumps(p).encode(), method='POST')
      req.add_header("Authorization", f"Bearer {T}"); req.add_header("Content-Type", "application/json")
      try:
        with url_request.urlopen(req) as r: return json.loads(r.read().decode()).get('job')
      except: return "ERR"
    def db_save(u, g):
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("INSERT INTO chat_history (u_in, g_out) VALUES (%s, %s)", (u, g));conn.commit();cur.close();conn.close()
      except: pass
    @app.route("/", methods=["GET", "POST"])
    def chat():
      if request.method == "POST":
        m = request.form.get("msg")
        cp = client.chat.completions.create(model="gpt-4o", messages=[{"role": "system", "content": "K8s Provisioner. YAML ONLY for changes. Text for questions."}, {"role": "user", "content": m}])
        r = cp.choices[0].message.content
        if "kind:" in r:
          j = trig(r, any(w in m.lower() for w in ["delete","remove"])); f = r + f"\n\n🚀 JOB: {j}"
        else: f = r
        db_save(m, f); return redirect(url_for('chat'))
      h = []
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword",connect_timeout=3)
        cur=conn.cursor();cur.execute("SELECT u_in, g_out FROM chat_history ORDER BY id ASC;");h=cur.fetchall();cur.close();conn.close()
      except: pass
      return render_template_string("""
    <!DOCTYPE html><html><head><style>
    body{font-family:sans-serif;margin:0;display:flex;height:100vh}
    #sb{width:220px;background:#202123;color:#fff;padding:10px}
    .main{flex:1;display:flex;flex-direction:column}
    .chat-area{flex:1;overflow-y:auto;padding:20px 10%;display:flex;flex-direction:column;gap:10px}
    .m{padding:10px;border-radius:10px;max-width:85%;white-space:pre-wrap;font-size:13px}
    .u{align-self:flex-end;background:#007bff;color:#fff}
    .a{align-self:flex-start;background:#f7f7f8;border:1px solid #ddd}
    form{padding:20px;display:flex;gap:10px}
    input{flex:1;padding:10px;border-radius:20px;border:1px solid #ddd}
    </style></head><body>
    <div id="sb"><b>HISTORY</b><hr>{% for row in history %}<div style="font-size:11px;margin-bottom:5px">💬 {{row[0][:20]}}</div>{% endfor %}</div>
    <div class="main">
      <div style="padding:10px;border-bottom:1px solid #eee"><b>NTI Zero-Touch</b> <a href="/clear" style="float:right">+ New</a></div>
      <div class="chat-area" id="c">{% for row in history %}<div class="m u">{{row[0]}}</div><div class="m a">{{row[1]}}</div>{% endfor %}</div>
      <form method="POST"><input type="text" name="msg" placeholder="Ask or Deploy..." required><button type="submit">➤</button></form>
    </div><script>document.getElementById('c').scrollTop=99999;</script></body></html>""", history=h)
    @app.route("/clear")
    def clear():
      try:
        conn=psycopg2.connect(host="postgres",database="appdb",user="appuser",password="supersecretpassword");cur=conn.cursor();cur.execute("DELETE FROM chat_history;");conn.commit();cur.close();conn.close()
      except: pass
      return redirect(url_for('chat'))
    if __name__ == "__main__":
      app.run(host="0.0.0.0", port=5000)
