apiVersion: v1
kind: Namespace
metadata:
  name: demo-webdb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-webdb
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: supersecretpassword
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-webdb
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo-webdb
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: demo-webdb
spec:
  replicas: 1
  selector:
    matchLabels: { app: adminer }
  template:
    metadata:
      labels: { app: adminer }
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: demo-webdb
spec:
  selector: { app: adminer }
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
